baseurl = "https://neohung.github.io/"
languagecode = "zh-TW"
title = "Neo"
author = "NeoH"
canonifyurls = true
theme = "blist"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "尼歐的blog"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "https://github.com/neohung"
[[menu.main]]
    name = "Projects"
    url  = "https://github.com/neohunge"
[[menu.main]]
    name = "Resume"
    url  = "https://github.com/neohung"
